# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwidow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(978, 610)
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        MainWindow.setIconSize(QtCore.QSize(18, 18))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_27 = QtWidgets.QLabel(self.groupBox)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 1, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        self.label_26.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 0, 0, 1, 1)
        self.comboBox_baud = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_baud.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_baud.setObjectName("comboBox_baud")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_baud, 1, 1, 1, 2)
        self.label_28 = QtWidgets.QLabel(self.groupBox)
        self.label_28.setStyleSheet("background:rgb(85, 170, 255)")
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 2, 0, 1, 1)
        self.comboBox_com = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_com.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_com.setObjectName("comboBox_com")
        self.gridLayout_2.addWidget(self.comboBox_com, 0, 1, 1, 2)
        self.pushButton_uart_sw = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_uart_sw.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_uart_sw.setObjectName("pushButton_uart_sw")
        self.gridLayout_2.addWidget(self.pushButton_uart_sw, 2, 2, 1, 1)
        self.pushButton_uart_rfresh = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_uart_rfresh.sizePolicy().hasHeightForWidth())
        self.pushButton_uart_rfresh.setSizePolicy(sizePolicy)
        self.pushButton_uart_rfresh.setMinimumSize(QtCore.QSize(0, 33))
        self.pushButton_uart_rfresh.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_uart_rfresh.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_uart_rfresh.setIconSize(QtCore.QSize(12, 12))
        self.pushButton_uart_rfresh.setObjectName("pushButton_uart_rfresh")
        self.gridLayout_2.addWidget(self.pushButton_uart_rfresh, 2, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.plainTextEdit_rx = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_rx.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.plainTextEdit_rx.setReadOnly(True)
        self.plainTextEdit_rx.setCenterOnScroll(True)
        self.plainTextEdit_rx.setObjectName("plainTextEdit_rx")
        self.gridLayout_4.addWidget(self.plainTextEdit_rx, 0, 1, 2, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_show_ascii = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_show_ascii.setMinimumSize(QtCore.QSize(0, 33))
        self.radioButton_show_ascii.setCheckable(True)
        self.radioButton_show_ascii.setChecked(True)
        self.radioButton_show_ascii.setAutoExclusive(True)
        self.radioButton_show_ascii.setObjectName("radioButton_show_ascii")
        self.gridLayout.addWidget(self.radioButton_show_ascii, 0, 0, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_save.setMinimumSize(QtCore.QSize(0, 33))
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 1, 0, 1, 1)
        self.radioButton_show_hex = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_show_hex.setMinimumSize(QtCore.QSize(0, 33))
        self.radioButton_show_hex.setChecked(False)
        self.radioButton_show_hex.setObjectName("radioButton_show_hex")
        self.gridLayout.addWidget(self.radioButton_show_hex, 0, 1, 1, 1)
        self.pushButton_clean = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_clean.setMinimumSize(QtCore.QSize(0, 33))
        self.pushButton_clean.setObjectName("pushButton_clean")
        self.gridLayout.addWidget(self.pushButton_clean, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton_tx_ascii = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_tx_ascii.setMinimumSize(QtCore.QSize(0, 33))
        self.radioButton_tx_ascii.setCheckable(True)
        self.radioButton_tx_ascii.setChecked(True)
        self.radioButton_tx_ascii.setAutoExclusive(True)
        self.radioButton_tx_ascii.setObjectName("radioButton_tx_ascii")
        self.gridLayout_3.addWidget(self.radioButton_tx_ascii, 0, 0, 1, 1)
        self.radioButton_tx_hex = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_tx_hex.setMinimumSize(QtCore.QSize(0, 33))
        self.radioButton_tx_hex.setChecked(False)
        self.radioButton_tx_hex.setObjectName("radioButton_tx_hex")
        self.gridLayout_3.addWidget(self.radioButton_tx_hex, 0, 1, 1, 1)
        self.pushButton_tx = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_tx.setMinimumSize(QtCore.QSize(0, 33))
        self.pushButton_tx.setObjectName("pushButton_tx")
        self.gridLayout_3.addWidget(self.pushButton_tx, 1, 0, 1, 1)
        self.pushButton_clean_tx = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_clean_tx.setMinimumSize(QtCore.QSize(0, 33))
        self.pushButton_clean_tx.setObjectName("pushButton_clean_tx")
        self.gridLayout_3.addWidget(self.pushButton_clean_tx, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.plainTextEdit_tx = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_tx.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.plainTextEdit_tx.setObjectName("plainTextEdit_tx")
        self.gridLayout_4.addWidget(self.plainTextEdit_tx, 2, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 4)
        self.gridLayout_4.setRowStretch(0, 3)
        self.gridLayout_4.setRowStretch(1, 2)
        self.gridLayout_4.setRowStretch(2, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(140, 150, 120, 80))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 978, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "串口调试助手"))
        self.groupBox.setTitle(_translate("MainWindow", "串口选择"))
        self.label_27.setText(_translate("MainWindow", "波特率"))
        self.label_26.setText(_translate("MainWindow", "选择"))
        self.comboBox_baud.setItemText(0, _translate("MainWindow", "115200"))
        self.comboBox_baud.setItemText(1, _translate("MainWindow", "9600"))
        self.comboBox_baud.setItemText(2, _translate("MainWindow", "38400"))
        self.label_28.setText(_translate("MainWindow", "操作"))
        self.pushButton_uart_sw.setText(_translate("MainWindow", "打开串口"))
        self.pushButton_uart_rfresh.setText(_translate("MainWindow", "刷新"))
        self.groupBox_2.setTitle(_translate("MainWindow", "接收选项"))
        self.radioButton_show_ascii.setText(_translate("MainWindow", "文本显示"))
        self.pushButton_save.setText(_translate("MainWindow", "保存"))
        self.radioButton_show_hex.setText(_translate("MainWindow", "十六进制显示"))
        self.pushButton_clean.setText(_translate("MainWindow", "清除接收"))
        self.groupBox_3.setTitle(_translate("MainWindow", "发送选项"))
        self.radioButton_tx_ascii.setText(_translate("MainWindow", "文本显示"))
        self.radioButton_tx_hex.setText(_translate("MainWindow", "十六进制显示"))
        self.pushButton_tx.setText(_translate("MainWindow", "发送"))
        self.pushButton_clean_tx.setText(_translate("MainWindow", "清除发送"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "常规"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Tab 1"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "PID调参"))

